Added talk 05-19
devopsmalmo/meetups pull request #41
Opened 2021-04-26 12:55 UTC by velith

2021-04-26 13:27 UTC, gangsta requested changes

2021-04-26 13:27 UTC, gangsta commented on README.md
> +- [X] *2021-05-19* - Lessons Learned - Short story about measuring DevOps performance [Fredrin Stål](talks/fredrik-metrics.md)
should be `Fredrin Stål -> Fredrik Stål`

2021-04-28 09:20 UTC, kvarak approved these changes

2021-04-28 09:21 UTC, kvarak commented
It would be good if you interactively rebased this branch before merging to get a nicer history :)

2021-04-28 09:23 UTC, velith commented
You mean squash?

2021-04-28 11:14 UTC, gangsta approved these changes
LGTM

2021-04-28 11:24 UTC, merged